title:            Choestelus StackTrace
description:      Insignificant Blog
disqus_shortname:
reading_time:     false
words_per_minute: 200
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
url: http://choestelus.github.io

# Owner/author information
owner:
  name:           Choestelus
  avatar:         avatar.png
  bio:            "The [almost] Insignificant Being"
  email:
  # Social networking links used in footer. Update and remove as you like.
  twitter:        
  facebook:       
  github:         
  stackexchange:  
  linkedin:       
  instagram:      
  flickr:         
  tumblr:         
  # google plus id, include the '+', eg +mmistakes
  google_plus:    +ChoestelusChCh

# Background image to be tiled on all pages
background: 

# Analytics and webmaster tools stuff goes here
google_analytics:   
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Bangkok
future:      true
highlighter: pygments
markdown:    kramdown
gems:
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]

prose:
	site: "http://choestelus.github.io"
    media: "images"
    metadata:
      "_posts": |
        - name: "layout"
          field:
            element: "hidden"
              value: "post"
              
        - name: "modified"
          field:
            element: "text"
            label: "Time modified"
            value: CURRENT_DATETIME
            
        - name: "title"
          field:
            element: "text"
            label: "title"
            placeholder: "Awesome title here!"
            
        - name: "comments"
          field:
            element: "checkbox"
            label: "Allow comments"
            value: false
            
        - name: "share"
          field:
            element: "checkbox"
            label "Allow sharing"
            value: true
        
        - name: "tags"
          field:
            element: "multiselect"
            label: "Add Tags"
            placeholder: "Choose Tags"
            alterable: true
            options:
              - name: "Apples"
                value: "apples"
              - name: "Bananas"
                value: "bananas"
              - name: "Pears"
                value: "pears"
              - name: "Mangos"
                value: "mangos"
